### ISSUE TITLE
코드리뷰 

### ISSUE THREAD

**Issue by jjunyjjuny** [woowa-techcamp-2021/cashbook-14#21]
#5 

다른 코드도 다 봐야하는데 컴포넌트 작성하신거만 쳐다보다가 시간이 다 지나갔네요.. 

이렇게 복잡한 구조를 이렇게 빨리 진행하시다니 그저 빛..

**Comment by danmin20** [comment]
다 (영준님을 포함한) 뛰어난 분들의 레퍼런스 코드 덕분입니다..
