### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by negu63** [woowa-techcamp-2021/cashbook-14#22]
이 팀은 세 명이 아닌가 싶었습니다ㅋㅋㅋ
너무 잘 봤고 많이 배우고 갑니다!

**Comment by danmin20** [comment]
중국 하청ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그럴리가요... 아직... 할 게 너무 많습..니다 흑흑

**Comment by KangyeolLee** [comment]
아니 쉬엄쉬엄 하세요

**Comment by danmin20** [comment]
전 하루종일 놀기만 하는 걸요...
